module Tests.DimensionalCausality

import QuickCheck
import Math.FiberBundle
import Physics.Evolution.QuantumGates
import Tests.Common

%default total

||| Mathematically validates that any Spacetime manifold strictly conserves
||| dimensional causality (only known Prime Gates or Vacuum exist in the history).
public export
isValidCausality : Nat -> Bool
isValidCausality 1 = True -- Vacuum Root
isValidCausality 2 = True -- Background
isValidCausality 3 = True -- Matter
isValidCausality 5 = True -- Charge
isValidCausality 7 = True -- Time
isValidCausality 11 = True -- Weak Force
isValidCausality 13 = True -- Resonance
isValidCausality _ = False

public export
verifyTimeline : SpacetimeManifold -> Bool
verifyTimeline (Root _ geom) = isValidCausality (dimensions geom)
verifyTimeline (Node _ parent _ geom) = isValidCausality (dimensions geom) && verifyTimeline parent

||| Proves that the timeline natively generated by QuickCheck's Spacetime engine
||| never breaks fundamental quantum rules!
|||
||| Why this matters:
||| We recursively traverse backwards through time, checking the geometric 
||| scale (dimension) of every single historic epoch. If this test passes, it 
||| is mathematically impossible for the universe to accidentally synthesize
||| a non-prime or invalid dimension (e.g. S_4 or S_8) during cosmological unfolding.
public export
prop_strictCausality : Property
prop_strictCausality = forAll genSpacetime (MkFn (\tree => property (verifyTimeline tree)))
