[custom.all.Linear-Physics]
type = "local"
path = "."
ipkg = "Linear-Physics.ipkg"

[custom.all.idris2-LUniverse]
type = "local"
path = "idris2-LUniverse"
ipkg = "idris2-LUniverse.ipkg"

[custom.all.idris2-chromogeometry]
type = "local"
path = "idris2-chromogeometry"
ipkg = "idris2-chromogeometry.ipkg"

[custom.all.idris2-Maxel]
type = "local"
path = "idris2-Maxel"
ipkg = "idris2-Maxel.ipkg"

[custom.all.idris2-Multiset-Advanced]
type = "local"
path = "idris2-Multiset-Advanced"
ipkg = "idris2-Multiset-Advanced.ipkg"

[custom.all.idris2-ref1]
type = "local"
path = "../Library/Src/idris2-ref1"
ipkg = "ref1.ipkg"

[custom.all.idris2-QuickCheck]
type = "local"
path = "idris2-QuickCheck"
ipkg = "idris2-QuickCheck.ipkg"

[custom.all.idris2-LUniverse-Tests]
type = "local"
path = "idris2-LUniverse-Tests"
ipkg = "idris2-LUniverse-Tests.ipkg"
